### ISSUE TITLE
Zoom in/ out implementation

### ISSUE THREAD

**Issue by agporto** [andfanilo/streamlit-drawable-canvas#111]
@andfanilo Thanks for this great library. I was trying to implement zoom in/out of the canvas and I got it to work great on canvas objects (see file attached). For some reason, however, the background image does not respond to mouse events.  Any chance you might know what is causing it? 
[DrawableCanvas_mod.txt](https://github.com/andfanilo/streamlit-drawable-canvas/files/11010465/DrawableCanvas_mod.txt)

**Comment by andfanilo** [comment]
Hello @agporto ,

Are you able to make a PR, just to make it easier for me to view the code changes? We can close it afterwards if you then want to do a proper one.

Judging from https://stackoverflow.com/questions/16980273/html-5-how-to-zoom-canvas-background-image, It might be you need to redraw a scaled version of the image on the background canvas, though I didn't dig further

Anyway that looks awesome, hope it works out for you!

Have a nice day,
Fanilo

**Comment by agporto** [comment]
Closing for now, since I submitted the PR. #112
