### ISSUE TITLE
Not working on huggingface spaces

### ISSUE THREAD

**Issue by bertChristiaens1** [andfanilo/streamlit-drawable-canvas#113]
Hi, I am trying your canvas on the huggingface spaces and it seems to just give an empty white background instead of the chosen background image. Is this a known issue?

**Comment by MohannadEhabBarakat** [comment]
I have the same issue. @bertChristiaens1 Any luck solving it?

**Comment by andfanilo** [comment]
Aaahhh ... hmmm yeah, does it work if you downgrade drawable canvas to 0.8.0?

**Comment by whitphx** [comment]
Hi, it looks like this problem occurs when some query params or url hashes are added to the URL.
For example, even in local development, we can find this problem accessing `http://localhost:8501/#foo`.

HF Spaces attaches query params and hashes to the iframe URL and it seems to be why this problem occurs.
