### ISSUE TITLE
Clean the cache when rerun the function st_canvas()

### ISSUE THREAD

**Issue by Yangxiaojun1230** [andfanilo/streamlit-drawable-canvas#21]
Hi author,
     Awesome work and really helpful to me.  Now I realized automatically show photo in canvas and save the image. But I wonder how to clear the canvas when I show a new photo. Could you give me some suggestion?

**Comment by andfanilo** [comment]
Hey @Yangxiaojun1230, thanks for the kind works :) 

I'm currently on #16 clearing the drawings with a button, so you will be able to delete all drawings after changing photo by the click of a button. 
I've actually been considering clearing the drawing on background_image change, maybe I'll do it, I don't have a reason to preserve drawings on image change. What do you think?

Fanilo
