### ISSUE TITLE
Export canvas as png

### ISSUE THREAD

**Issue by alexcg1** [andfanilo/streamlit-drawable-canvas#28]
I'm working on a front end for a neural search framework to take a user's drawing and match it with the closest looking Pokemon: https://github.com/alexcg1/jina-streamlit-frontend

My goal is to have the user draw on the canvas, then click button to export that drawing into a base64 encoded png, which I then pass to Jina via REST API.

How can I take the `np.ndarray` generated by the canvas and convert that to a png? I've been trying a few things so far, but all I get is a blank transparent png in the canvas dimensions.

I'm working on the code in the `draw` branch: https://github.com/alexcg1/jina-streamlit-frontend/tree/draw

Thanks for putting together a cool project. I can't wait to get it working!

**Comment by alexcg1** [comment]
(Note: if you do want to play with my code, when `app.py` is running, select `Draw` from the Media selectbox)

**Comment by andfanilo** [comment]
Hey @alexcg1, thanks for the kind words, really appreciate it :smile: 

It looks like the following snippet works on my side: 

```python
import streamlit as st
from streamlit_drawable_canvas import st_canvas
from PIL import Image

data = st_canvas()
if data is not None:
    img_data = data.image_data
    if st.button("Save image as PNG"):
        im = Image.fromarray(img_data.astype('uint8'), mode="RGBA")
        im.save("test.png", "PNG")
```

Hope it helps you!

> I can't wait to get it working! 

BW are you going to make the app available on [Streamlit Sharing](https://www.streamlit.io/sharing) :wink: ?

Cheers,
Fanilo

**Comment by alexcg1** [comment]
> BW are you going to make the app available on [Streamlit Sharing](https://www.streamlit.io/sharing) wink ?

For sure!

Thanks for the speedy assist. I'll give this a shot tomorrow and see how it pans out

**Comment by alexcg1** [comment]
Worked perfectly, thanks! I'll write up a blog post then later submit to Streamlit Sharing!

**Comment by andfanilo** [comment]
Great, I will be closing this then :) looking forward to the app!

**Comment by alexcg1** [comment]
And here's the app! https://share.streamlit.io/jina-ai/integration-streamlit-advanced/main/app.py

(I still need to get back-end endpoint hooked up from our end to make it work, but as soon as that's done, you'll be searching Pokemon in no time!)

**Comment by andfanilo** [comment]
Cool!!!!

Definiterly post it on the [forums](https://discuss.streamlit.io/c/streamlit-examples/9) when it's done cooking ;)

Cheers,
Fanilo
