### ISSUE TITLE
Add background image

### ISSUE THREAD

**Issue by andfanilo** [andfanilo/streamlit-drawable-canvas#3]
Add background image. Maybe implies sending only drawing instead of full image data on mouse up

**Comment by angelicaba23** [comment]
Hello I'm trying to load a bg image but doesn't work for me, can you pls help me. Thanks in advance.
[repo](https://github.com/angelicaba23/app-super-resolution/tree/dev)
[deployed app](https://share.streamlit.io/angelicaba23/app-super-resolution/dev/app.py)

<img width="710" alt="Screen Shot 2022-03-26 at 12 15 51 PM" src="https://user-images.githubusercontent.com/72242331/160250350-ec7fde3d-fedb-4c26-b5b5-0eae42b904aa.png">
