### ISSUE TITLE
how to obtain the center when drawing a circle

### ISSUE THREAD

**Issue by longswordinhand** [andfanilo/streamlit-drawable-canvas#32]
Is the (left, top) the left-top point of the circle? I found there is an offset if I use it.
Thanks.

**Comment by andfanilo** [comment]
Hey @longswordinhand,

You can refer to this answer: https://github.com/andfanilo/streamlit-drawable-canvas/issues/15#issuecomment-687751606

```python
center_x = left + radius * math.cos(angle * math.pi / 180)
center_y = top + radius * math.sin(angle * math.pi / 180)
```
