### ISSUE TITLE
Your app is having trouble loading the streamlit_drawable_canvas.st_canvas component.

### ISSUE THREAD

**Issue by Cm744** [andfanilo/streamlit-drawable-canvas#33]
I get this error message in my app website instead of canvas area, 

"Your app is having trouble loading the streamlit_drawable_canvas.st_canvas component.

(The app is attempting to load the component from http://localhost:3001, and hasn't received its "streamlit:componentReady" message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?
For more troubleshooting help, please see the Streamlit Component docs or visit our forums."

I will be grateful if can help me solve it.

**Comment by andfanilo** [comment]
Hello @Cm744, thanks for reaching!

How did you install `streamlit-drawable-canvas`? What version are you using? It may be that you should use `streamlit-drawable-canvas-0.5.1` as version 0.5.0 is buggy.

Fanilo

**Comment by andfanilo** [comment]
Closing this, feel free to reopen if necessary!
