### ISSUE TITLE
Feature request: tag annotations

### ISSUE THREAD

**Issue by robmarkcole** [andfanilo/streamlit-drawable-canvas#41]
I am annotation regions of interest (ROI) and displaying them in a dataframe for [a text extraction app](https://github.com/robmarkcole/aws-text-extraction-app). I would like to auto generate an incrementing tag for the regions, e.g. region_1, region_2 etc and have this displayed inside the annotation and also in the dataframe, so that people can associate the data. Is this currently possible, or a feature request?
Cheers and great work!

![image](https://user-images.githubusercontent.com/11855322/107110442-b131ee80-683f-11eb-803b-105e22b70a6d.png)

**Comment by andfanilo** [comment]
This has been on my mind for a while, and [I know it's possible](http://fabricjs.com/fabric-intro-part-3#subclassing).

But it's not yet something that I had prioritized. Maybe you can check out https://discuss.streamlit.io/t/new-component-streamlit-labelstudio-allows-you-to-embed-the-label-studio-annotation-frontend-into-your-application/9524, and tell me if it does the trick ? I have yet to test it :) if it doesn't fit your needs I'll check out on adding this.

**Comment by robmarkcole** [comment]
Thanks for the link, label studio does look awesome and obviously designed for annotation. I still think this is a valuable feature addition as I imagine it is a common use case to be able to reference annotations elsewhere in an app

**Comment by robmarkcole** [comment]
I am currently trying the approach below, where I want to associate the label_name with the stroke_colour. Any suggestions how I can cache this releationship, in order to show the correct label/colour combo in the dataframe? 

![image](https://user-images.githubusercontent.com/11855322/107137282-fe2ac900-6902-11eb-9a2b-dea6dfb21833.png)

**Comment by robmarkcole** [comment]
Alright I kinda hacked together using a persistent dict

![image](https://user-images.githubusercontent.com/11855322/107142141-c16fc980-6924-11eb-9637-2ec264bc21a9.png)

Source https://github.com/robmarkcole/aws-text-extraction-app/blob/ISSUE1/app/app.py

**Comment by andfanilo** [comment]
https://share.streamlit.io/andfanilo/streamlit-drawable-canvas-demo/app.py in page "Color based image annotation"

Ahah I was just building you an example with SessionState but looks like you managed before me :rofl:

**Comment by robmarkcole** [comment]
Looks like you settled on a very similar approach! In your demo I get an error:

![image](https://user-images.githubusercontent.com/11855322/107143015-8b354880-692a-11eb-9b09-f2c1853f20c4.png)

**Comment by andfanilo** [comment]
Hmmmm this is odd, I reported this [here](https://github.com/streamlit/streamlit/issues/2689) and I thought it was fixed but it seems it isn't depending on users ?
What system/browser are you on?

**Comment by andfanilo** [comment]
> The ability to clear the state will be useful

Yeaaaah...I'll let this as an user exercise :) also Session State should be "official" soonish in Streamlit so I'll be waiting for this before further changes ;)

**Comment by robmarkcole** [comment]
What system/browser are you on? -> Chrome, Big Sur

Re sessions state, my workaround is to kill and rerun the app

**Comment by andfanilo** [comment]
Does it happen on https://share.streamlit.io/andfanilo/s4a-color-picker-bug/main/app.py? Will see if I reopen the issue then.

**Comment by andfanilo** [comment]
Also since we have 2 workarounds now on image annotation, I'll close this soon except if you have other things to add ;)

**Comment by robmarkcole** [comment]
Still an issue on that link you provided

![image](https://user-images.githubusercontent.com/11855322/107145374-ee2ddc00-6938-11eb-84bf-11012f86310d.png)

I will close this feature request
