### ISSUE TITLE
Json_data hex color 

### ISSUE THREAD

**Issue by muhammadAgfian96** [andfanilo/streamlit-drawable-canvas#43]
Hi, Thanks for amazing projects, relly helpful.

In choosing color section, can we choose the output of stroke color is rgb (xxx,xxx,xx) since opencv default is read rgb color.
yup, i know we can converting hex to rgb with python. just asking cause really exciting! 

Thanks in advance!

**Comment by andfanilo** [comment]
Hi @muhammadAgfian96, loving your enthusiasm :) 

What I'm sending back to Streamlit is the raw output of the Javascript library I'm using underneath, and I don't think I have an easy control on how to export the path color. I think you'll be much faster by converting on the Python side than me on the JS side, so I'd rather go with your solution.

I'd be grateful if you could post a small snippet of the color conversion in the issue btw so other users can refer to it if necessary.

Have a nice day!
Fanilo

**Comment by muhammadAgfian96** [comment]
ah i see, thanks for your response!
