### ISSUE TITLE
Upload new background to existing canvas

### ISSUE THREAD

**Issue by PytaichukBohdan** [andfanilo/streamlit-drawable-canvas#54]
I try uploading a new image to the ```background_image=NEW_IMAGE``` property while initializing the canvas.
The background is changed, but the new height and weight are not. Which makes this canvas unusable.

Deleting this canvas object and creating a new one doesn't help.

Is there any way to do so?

**Comment by PytaichukBohdan** [comment]
Fixed it :)

I just removed the "key" assignment while initializing

**Comment by SaiNikhileshReddy** [comment]
@PytaichukBohdan can you provide more info on how you resolved it. I'm having similar issue.
