### ISSUE TITLE
SecurityError: Blocked a frame with origin

### ISSUE THREAD

**Issue by robmarkcole** [andfanilo/streamlit-drawable-canvas#55]
When I try to change the colour in the annotation demo I get this error:
![image](https://user-images.githubusercontent.com/11855322/120960487-da15b200-c753-11eb-97e1-c19be5c43d30.png)

**Comment by andfanilo** [comment]
Yeah unfortunately :( https://github.com/streamlit/streamlit/issues/2689 you could add a +1 to this issue.

Fanilo

**Comment by andfanilo** [comment]
This should be solved now @robmarkcole
