### ISSUE TITLE
TypeError: _lib__WEBPACK_IMPORTED_MODULE_7__.tools[drawingMode] is not a constructor

### ISSUE THREAD

**Issue by matpz** [andfanilo/streamlit-drawable-canvas#62]
Hi, I'm trying to locally run an application that uses streamlit-drawable-canvas.

I have followed the procedure for the development mode, but once started in place of the drawing component I get the error reported in the title.

I copy below the entire error log:

TypeError: _lib__WEBPACK_IMPORTED_MODULE_7__.tools[drawingMode] is not a constructor
(anonymous function)
C:/WORK/streamlit-drawable-canvas-develop/streamlit_drawable_canvas/frontend/src/DrawableCanvas.tsx:141

>138 |  */
   139 | useEffect(() => {
   140 |   // Update canvas events with selected tool
   141 |   const selectedTool = new tools[drawingMode](canvas) as FabricTool
   142 |  ^ const cleanupToolEvents = selectedTool.configureCanvas({
   143 |     fillColor: fillColor,
   144 |     strokeWidth: strokeWidth,

Thank you in advance.

**Comment by matpz** [comment]
Hi @andfanilo, if it can be useful, the problem disappeared by installing the pinned version 0.1.1. Thank you and regards.

**Comment by andfanilo** [comment]
Awesome, thanks for coming back with the answer! Yeah webpack versions can get pretty picky :/

Have fun developing on the canvas 🎈 
Fanilo
