### ISSUE TITLE
Finding the starting point and end point of a line

### ISSUE THREAD

**Issue by MohamedGAmin** [andfanilo/streamlit-drawable-canvas#72]
First, I would like to thank you for this great component.
I have a simple question. May I know how to extract the x1,y1,x2 and y2 of a line from canvas_result?

As I will need to know starting point and the end point of the line.

**Comment by chraibi** [comment]
I think it would be something like this: 

```
X1 = np.array(objects['left'])
Y1 = np.array(objects['top'])
X2 = np.array(objects['left']+objects['width'])
Y2 = np.array(objects['top']+objects['height'])
```

**Comment by andfanilo** [comment]
Thanks for chiming in @chraibi !

Also if you scale your objects on the canvas you may need to apply the scale factor `objects['scaleX']` and `objects['scaleY']`

Have a nice day,
Fanilo

**Comment by chraibi** [comment]
Oh yes. And maybe also rotation?

```
X1 = objects['scaleX'] * np.array(objects['left'] * np.cos(objects["angle"] * np.pi / 180))
```
