### ISSUE TITLE
Background image does not show up

### ISSUE THREAD

**Issue by chraibi** [andfanilo/streamlit-drawable-canvas#76]
I want to draw on a canvas with some background.
What I do is the following:
- Draw some points in a `fig`
- convert `fig` to image with `PIL` and  use this as canvas background. See this [function](https://github.com/chraibi/jupedsim-dashboard/blob/main/draw_lines.py#L16)

Locally, it works fine:

<img width="265" alt="Screen Shot 2022-04-30 at 14 33 30" src="https://user-images.githubusercontent.com/5772973/166105780-1d726593-6ee8-494b-b37d-a3e4a88700f9.png">

But not on streamlit

https://share.streamlit.io/chraibi/jupedsim-dashboard/main/draw_lines.py

Any idea what might be wrong with my setup?

**Comment by andfanilo** [comment]
Yeah unfortunately a known issue on 0.9.0 I have yet to fix #70 :/ I'll have to look into it someday! I'll try tomorrow if I have a bit of time
