### ISSUE TITLE
dark theme toolbar

### ISSUE THREAD

**Issue by yann-ro** [andfanilo/streamlit-drawable-canvas#78]
Hi and thank you for this amazing work !
Is there a way to inverse color of toolbar (black/white) using dark theme ?
<img width="376" alt="image" src="https://user-images.githubusercontent.com/52059549/169068996-7027bdda-af81-4e5f-b165-42f972b9fe8e.png">

**Comment by andfanilo** [comment]
Yeah that's a problem which is reported in #63 , I'll close this one as a duplicate if you don't mind :) 

Cheers,
Fanilo
