### ISSUE TITLE
bug blinking canvas

### ISSUE THREAD

**Issue by yann-ro** [andfanilo/streamlit-drawable-canvas#79]
I report my problem in streamlit discuss : [https://discuss.streamlit.io/t/window-blinking-when-double-clicking-or-using-package-streamlit-drawable-canvas/25351](url)

and I see the same bug on the reference demo : [https://share.streamlit.io/andfanilo/streamlit-drawable-canvas-demo/master/app.py](url)

when we navigate to a different page several times, the website window suddenly flashes and everything is reset.

Do you have any idea what the problem is? and maybe how to fixit ?

**Comment by andfanilo** [comment]
Hi @yann-ro 

Are you maybe able to build a smaller, reproducible example of your bug, or maybe an example where everything fits in a single script? 
Also I'm in a seminar for the week so I won't be able to work on this immediately :/ 

Thanks in advance,
Fanilo

**Comment by yann-ro** [comment]
Yep I downgrade to version 0.7.0 and it fixit ! (now i can't use polygon but rect will do the job for the moment)
Thank you !
