### ISSUE TITLE
Background image does not display

### ISSUE THREAD

**Issue by robmarkcole** [andfanilo/streamlit-drawable-canvas#86]
Running the example app locally, the background image is not displaying

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/11855322/188486712-3ca6afbd-9e2d-470b-9bd5-02c8b58c261e.png">

**Comment by robmarkcole** [comment]
It did occur to me that this might be the designed behaviour - if so please close :-)

**Comment by andfanilo** [comment]
Yeah it is the designed behavior, as you can superimpose the drawing with the image afterwards so I don't need to send back said image :)
